spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.99:3306/xzzz-blossom?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&&serverTimezone=GMT%2B8
    username: root
    password: jasmine888
    hikari:
      max-lifetime: 120000
  redis:
    # 单机模式
    host: 192.168.31.99
    port: 6379
    password:
    database: 0

logging:
  level:
    com.blossom: debug
    com.blossom.expand.tracker: info
    com.blossom.backend.base.auth: info
    org.springframework.boot.web.embedded.tomcat.TomcatWebServer: warn
    com.baomidou.dynamic.datasource.DynamicRoutingDataSource: warn
    com.zaxxer.hikari.HikariDataSource: warn
    org.apache.coyote.http11.Http11NioProtocol: warn

# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫ project ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
project:
  base: # 基础信息
    version: @project.version@
    ex:
      # 异常打印格式 all/project
      stack-trace: project
      # format/line
      format: format
    log: # 日志配置
      duration: 600000 # 动态日志级别 6 分钟后失效
      restore-duration: 30000 # 30 秒判断一次是否失效
  db:
    slow-interval: 10 # 慢SQL
  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫ Auth ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  auth: # 授权
    enabled: true # 开启授权
    # 授权 token 的方式, 注意, 如果使用 redis, 需要引入 redis 包, 否则会提示错误
    type: caffeine
    default-password: 123456 # 默认密码
    password-encoder: bcrypt # 加密方式
    clients: # 客户端
      - client-id: blossom
        grant-type: 'password'
        duration: 21600 # 客户端授权时间 6 小时
        multi-place-login: true # 客户端是否允许多地登录
    white-list: # 白名单
      - /sentinel/**
  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫ Cache/Redis ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  cache: # 缓存
    names-config: # 缓存键超时时间配置
      - name: test_cache1
        seconds: 10
  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫ Tracker ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  tracker:
    collector:
      enabled: false # 关闭收集器
      max-cache: 5000
      rate: 100
    repository:
      type: disk1 # 关闭存储
      disk:
        use-pid: true
        log-dir: /logs/tracker
  # ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┫  IAAS   ┣━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  iaas:
    os-type: blossom
    blos:
      # 请以 / 结尾
      domain: "http://localhost:9999/pic/"
      # 请以 / 结尾
      default-path: "/home/bl/img/"